name: Build & Release Executable

on:
    push:
        tags: ["v*"]

permissions:
    contents:
        write

jobs:
    build:
        runs-on: windows-latest

        env:
            exe: dist/Playlist Downloader.exe
    
        steps:
            -   uses: actions/checkout@v4

            -   name: Install Python
                uses: actions/setup-python@v5
                with:
                    python-version: "3.13"
            
            -   name: Install Dependencies
                run: |
                    pip install pyinstaller yt_dlp
            
            -   name: Build Executable
                run: |
                    pyinstaller main.spec
            
            -   name: Upload build artifacts
                uses: actions/upload-artifact@v4
                with:
                    name: Executable File
                    path: |
                        ${{env.exe}}
            
            -   name: Release Executable
                if: success()
                uses: softprops/action-gh-release@v1
                with:
                    tag_name: ${{github.ref_name}}
                    files: | 
                        ${{env.exe}}
            
            -   name: Delete tag on failure
                if: failure()
                run: |
                    git push origin --delete ${{github.ref_name}} || echo "" "Failed to delete tag!" ""
